---
- name: deploy docker
  hosts: all
  become: true
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: present
    - name: pull nginx image
      docker_image:
        name: nginx
        source: pull
    - name: run docker container
      docker_container:
        name: nginx_container
        image: nginx
        state: started
    - name: check status
      command: docker ps -a
      register: result
    - name: show result
      debug:
       var: result.stdout
