- name: sample playbook 2
  hosts: all
  become: yes
  tasks:
    - name: install apache web server
      apt:
        name: apache2
        state: latest
        update_cache: yes
      notify:
        - restart apache

    - name: Ensure apache is enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: generate config file
      template:
        src: temp.j2
        dest: /etc/nginx
        owner: root
        mode: '0644'
      vars:
        server_port: 9090
      notify:
        - restart apache

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
